# Generated by Django 3.2.8 on 2021-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateTimeField(verbose_name='due date')),
            ],
        ),
    ]
