# Generated by Django 3.2.6 on 2021-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211026_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(max_length=12),
        ),
    ]
