# Generated by Django 3.2.6 on 2021-10-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211026_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(max_length=12),
        ),
    ]
