# Generated by Django 3.2.6 on 2021-10-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20211027_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(max_length=30, verbose_name='due date'),
        ),
    ]
