# Generated by Django 3.2.6 on 2021-10-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_todo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todo')),
            ],
        ),
    ]
