# Generated by Django 3.2.6 on 2021-10-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('D', 'Deliverable'), ('OL', 'Optional Lab'), ('OC', 'Outcomes')], default='D', max_length=2),
        ),
    ]
