# Generated by Django 3.2.6 on 2021-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('D', 'Deliverable'), ('OL', 'Optional Lab'), ('OC', 'Outcomes'), ('PR', 'Project'), ('RL', 'Rewatch Lecture'), ('T', 'Tutorial'), ('0T', 'Other')], default='0T', max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
