# Generated by Django 3.2.6 on 2021-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211029_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='test',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
