# Generated by Django 3.2.6 on 2021-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_todo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='test',
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('D', 'Deliverable'), ('OL', 'Optional Lab'), ('OC', 'Outcomes'), ('PR', 'Project'), ('RL', 'Rewatch Lecture'), ('T', 'Tutorial'), ('0T', 'Other')], default='D', max_length=2),
        ),
    ]
